image:
  file: Dockerfile
ports:
  - port: 8001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
tasks:
  - init: touch /tmp/.npm-lock &&
            composer install &&
            rm /tmp/.npm-lock
    command: echo "Dependancies Installed"
  - name: MySQL
    command: >
        mysqld
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log

  - name: Migrate
    init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: >
          mysql -e 'create database cats';
          mysql -e 'use cats';
          php artisan migrate;
          php artisan db:seed;
          vendor/bin/phpunit;