image:
  file: Dockerfile
ports:
  - port: 8001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
tasks:
  - command: composer install
    command: echo "Dependancies Installed"
  - name: MySQL
    command: >
        mysqld
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log

  - name: Migrate
    command: >
          mysql -e 'create database cats';
          mysql -e 'use cats';
          php artisan migrate;
          php artisan db:seed;
  - name: Tests
    command: >
          vendor/bin/phpunit;
