image:
  file: Dockerfile
ports:
  - port: 8001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
tasks:
- init: >
      touch /tmp/.composer-lock &&
      composer install &&
      rm /tmp/.composer-lock
  - name: MySQL
    before: >
        mysqld
  - name: Apache
    before: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log
  - init: sleep 1 && while [ -f /tmp/.composer-lock ]; do sleep 1; done
    command: echo "Creating database";
          mysql -e 'create database cats';
          mysql -e 'use cats';
    command: php artisan migrate
    command: php artisan db:seed
    command: vendor/bin/phpunit
